import { Card } from './card';

export const CARDS: Card[] = [
  { id: 1, suit: '♦', rank: 1 },
  { id: 2, suit: '♦', rank: 2 },
  { id: 3, suit: '♦', rank: 3 },
  { id: 4, suit: '♦', rank: 4 },
  { id: 5, suit: '♦', rank: 5 },
  { id: 6, suit: '♦', rank: 6 },
  { id: 7, suit: '♦', rank: 7 },
  { id: 8, suit: '♦', rank: 8 },
  { id: 9, suit: '♦', rank: 9 },
  { id: 10, suit: '♦', rank: 10 },
  { id: 11, suit: '♦', rank: 11 },
  { id: 12, suit: '♦', rank: 12 },
  { id: 13, suit: '♦', rank: 13 },
  { id: 14, suit: '♥', rank: 1 },
  { id: 15, suit: '♥', rank: 2 },
  { id: 16, suit: '♥', rank: 3 },
  { id: 17, suit: '♥', rank: 4 },
  { id: 18, suit: '♥', rank: 5 },
  { id: 19, suit: '♥', rank: 6 },
  { id: 20, suit: '♥', rank: 7 },
  { id: 21, suit: '♥', rank: 8 },
  { id: 22, suit: '♥', rank: 9 },
  { id: 23, suit: '♥', rank: 1 },
  { id: 24, suit: '♥', rank: 1 },
  { id: 25, suit: '♥', rank: 1 },
  { id: 26, suit: '♥', rank: 1 },
  { id: 27, suit: '♠', rank: 1},
  { id: 28, suit: '♠', rank: 2 },
  { id: 29, suit: '♠', rank: 3 },
  { id: 30, suit: '♠', rank: 4 },
  { id: 31, suit: '♠', rank: 5 },
  { id: 32, suit: '♠', rank: 6 },
  { id: 33, suit: '♠', rank: 7 },
  { id: 34, suit: '♠', rank: 8 },
  { id: 35, suit: '♠', rank: 9 },
  { id: 36, suit: '♠', rank: 10 },
  { id: 37, suit: '♠', rank: 11 },
  { id: 38, suit: '♠', rank: 12 },
  { id: 39, suit: '♠', rank: 13 },
  { id: 40, suit: '♣', rank: 1 },
  { id: 41, suit: '♣', rank: 2 },
  { id: 42, suit: '♣', rank: 3 },
  { id: 43, suit: '♣', rank: 4 },
  { id: 44, suit: '♣', rank: 5 },
  { id: 45, suit: '♣', rank: 6 },
  { id: 46, suit: '♣', rank: 7 },
  { id: 47, suit: '♣', rank: 8 },
  { id: 48, suit: '♣', rank: 9 },
  { id: 49, suit: '♣', rank: 10 },
  { id: 50, suit: '♣', rank: 11 },
  { id: 51, suit: '♣', rank: 12 },
  { id: 52, suit: '♣', rank: 13 }
];
