import { Kortti } from './kortti';

export const KORTIT: Kortti[] = [
  { id: 1, maa: 'Ruutu', arvo: 1 },
  { id: 2, maa: 'Ruutu', arvo: 2 },
  { id: 3, maa: 'Ruutu', arvo: 3 },
  { id: 4, maa: 'Ruutu', arvo: 4 },
  { id: 5, maa: 'Ruutu', arvo: 5 },
  { id: 6, maa: 'Ruutu', arvo: 6 },
  { id: 7, maa: 'Ruutu', arvo: 7 },
  { id: 8, maa: 'Ruutu', arvo: 8 },
  { id: 9, maa: 'Ruutu', arvo: 9 },
  { id: 10, maa: 'Ruutu', arvo: 10 },
  { id: 11, maa: 'Ruutu', arvo: 11 },
  { id: 12, maa: 'Ruutu', arvo: 12 },
  { id: 13, maa: 'Ruutu', arvo: 13 },
  { id: 14, maa: 'Hertta', arvo: 1 },
  { id: 15, maa: 'Hertta', arvo: 2 },
  { id: 16, maa: 'Hertta', arvo: 3 },
  { id: 17, maa: 'Hertta', arvo: 4 },
  { id: 18, maa: 'Hertta', arvo: 5 },
  { id: 19, maa: 'Hertta', arvo: 6 },
  { id: 20, maa: 'Hertta', arvo: 7 },
  { id: 21, maa: 'Hertta', arvo: 8 },
  { id: 22, maa: 'Hertta', arvo: 9 },
  { id: 23, maa: 'Hertta', arvo: 1 },
  { id: 24, maa: 'Hertta', arvo: 1 },
  { id: 25, maa: 'Hertta', arvo: 1 },
  { id: 26, maa: 'Hertta', arvo: 1 },
  { id: 27, maa: 'Pata', arvo: 1},
  { id: 28, maa: 'Pata', arvo: 2 },
  { id: 29, maa: 'Pata', arvo: 3 },
  { id: 30, maa: 'Pata', arvo: 4 },
  { id: 31, maa: 'Pata', arvo: 5 },
  { id: 32, maa: 'Pata', arvo: 6 },
  { id: 33, maa: 'Pata', arvo: 7 },
  { id: 34, maa: 'Pata', arvo: 8 },
  { id: 35, maa: 'Pata', arvo: 9 },
  { id: 36, maa: 'Pata', arvo: 10 },
  { id: 37, maa: 'Pata', arvo: 11 },
  { id: 38, maa: 'Pata', arvo: 12 },
  { id: 39, maa: 'Pata', arvo: 13 },
  { id: 40, maa: 'Risti', arvo: 1 },
  { id: 41, maa: 'Risti', arvo: 2 },
  { id: 42, maa: 'Risti', arvo: 3 },
  { id: 43, maa: 'Risti', arvo: 4 },
  { id: 44, maa: 'Risti', arvo: 5 },
  { id: 45, maa: 'Risti', arvo: 6 },
  { id: 46, maa: 'Risti', arvo: 7 },
  { id: 47, maa: 'Risti', arvo: 8 },
  { id: 48, maa: 'Risti', arvo: 9 },
  { id: 49, maa: 'Risti', arvo: 10 },
  { id: 50, maa: 'Risti', arvo: 11 },
  { id: 51, maa: 'Risti', arvo: 12 },
  { id: 52, maa: 'Risti', arvo: 13 }
];
