import { Card } from './card';

export const CARDS: Card[] = [
  { id: 1, suit: 'Diamonds', rank: 1 },
  { id: 2, suit: 'Diamonds', rank: 2 },
  { id: 3, suit: 'Diamonds', rank: 3 },
  { id: 4, suit: 'Diamonds', rank: 4 },
  { id: 5, suit: 'Diamonds', rank: 5 },
  { id: 6, suit: 'Diamonds', rank: 6 },
  { id: 7, suit: 'Diamonds', rank: 7 },
  { id: 8, suit: 'Diamonds', rank: 8 },
  { id: 9, suit: 'Diamonds', rank: 9 },
  { id: 10, suit: 'Diamonds', rank: 10 },
  { id: 11, suit: 'Diamonds', rank: 11 },
  { id: 12, suit: 'Diamonds', rank: 12 },
  { id: 13, suit: 'Diamonds', rank: 13 },
  { id: 14, suit: 'Hearts', rank: 1 },
  { id: 15, suit: 'Hearts', rank: 2 },
  { id: 16, suit: 'Hearts', rank: 3 },
  { id: 17, suit: 'Hearts', rank: 4 },
  { id: 18, suit: 'Hearts', rank: 5 },
  { id: 19, suit: 'Hearts', rank: 6 },
  { id: 20, suit: 'Hearts', rank: 7 },
  { id: 21, suit: 'Hearts', rank: 8 },
  { id: 22, suit: 'Hearts', rank: 9 },
  { id: 23, suit: 'Hearts', rank: 1 },
  { id: 24, suit: 'Hearts', rank: 1 },
  { id: 25, suit: 'Hearts', rank: 1 },
  { id: 26, suit: 'Hearts', rank: 1 },
  { id: 27, suit: 'Spades', rank: 1},
  { id: 28, suit: 'Spades', rank: 2 },
  { id: 29, suit: 'Spades', rank: 3 },
  { id: 30, suit: 'Spades', rank: 4 },
  { id: 31, suit: 'Spades', rank: 5 },
  { id: 32, suit: 'Spades', rank: 6 },
  { id: 33, suit: 'Spades', rank: 7 },
  { id: 34, suit: 'Spades', rank: 8 },
  { id: 35, suit: 'Spades', rank: 9 },
  { id: 36, suit: 'Spades', rank: 10 },
  { id: 37, suit: 'Spades', rank: 11 },
  { id: 38, suit: 'Spades', rank: 12 },
  { id: 39, suit: 'Spades', rank: 13 },
  { id: 40, suit: 'Clubs', rank: 1 },
  { id: 41, suit: 'Clubs', rank: 2 },
  { id: 42, suit: 'Clubs', rank: 3 },
  { id: 43, suit: 'Clubs', rank: 4 },
  { id: 44, suit: 'Clubs', rank: 5 },
  { id: 45, suit: 'Clubs', rank: 6 },
  { id: 46, suit: 'Clubs', rank: 7 },
  { id: 47, suit: 'Clubs', rank: 8 },
  { id: 48, suit: 'Clubs', rank: 9 },
  { id: 49, suit: 'Clubs', rank: 10 },
  { id: 50, suit: 'Clubs', rank: 11 },
  { id: 51, suit: 'Clubs', rank: 12 },
  { id: 52, suit: 'Clubs', rank: 13 }
];
